"""Rename transactions table

Revision ID: 1f28ad404c7d
Revises: 75d23b45c72d
Create Date: 2026-04-19 21:23:05.674387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f28ad404c7d'
down_revision: Union[str, Sequence[str], None] = '75d23b45c72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appeal_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('type', sa.String(), server_default='dispersement', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('appeal_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeal_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('appeal_id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('type', sa.VARCHAR(), server_default=sa.text("'dispersement'"), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transfers')
    # ### end Alembic commands ###
