"""initial_schema

Revision ID: 5be154bbff5c
Revises: 
Create Date: 2026-04-26 08:19:15.816719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be154bbff5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('minecraft_username', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), server_default='0', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('discord_id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appealer_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('monthly_interest', sa.Float(), nullable=False),
    sa.Column('principal', sa.Float(), server_default='0', nullable=False),
    sa.Column('interest', sa.Float(), server_default='0', nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appeal_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('type', sa.String(), server_default='dispersement', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers')
    op.drop_table('appeals')
    op.drop_table('accounts')
    # ### end Alembic commands ###
