"""Appeal Transactions

Revision ID: 75d23b45c72d
Revises: f38f2ce46cee
Create Date: 2026-04-19 02:01:20.736904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d23b45c72d'
down_revision: Union[str, Sequence[str], None] = 'f38f2ce46cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('minecraft_username', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_table('appeal_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appeal_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), server_default='dispersement', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appeal_transactions')
    op.drop_table('accounts')
    # ### end Alembic commands ###
