"""Accounts

Revision ID: f38f2ce46cee
Revises: 2eec8d4c2bc7
Create Date: 2026-04-19 01:46:10.433028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38f2ce46cee'
down_revision: Union[str, Sequence[str], None] = '2eec8d4c2bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeals', sa.Column('remaining_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appeals', 'remaining_amount')
    # ### end Alembic commands ###
